Gene.bordegaray/2026/01/improve broadcast cache (#324)
## Context and Problem

closes #319 

### 1. Panics in tpcds
There have been panics after that look like:
```text
thread 'tokio-runtime-worker' panicked at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/datafusion-physical-plan-52.0.0/src/repartition/mod.rs:972:22: partition not used yet
```
This was happening because some operators (like TopK) cancel once
satisfied. When used with `BroadcastExec` this would cause issues with
the caching mechanism: since the consumer task was responsible for
populating the cache, if it was cancelled, the cache would not be
populated although it should be. Thus, the first consumer task would
execute partition, begin populating cache, abort it when cancelled,
second task would execute the same partition because cache not
populated.

### 2. Streaming Cache 
There was follow-up work noted to make the cache in broadcast
"streaming".
Prior to this, the cache was simple: the first task would collect all
batches from the input and populate the cache. This is not optimal as
there can be multiple subscribers that want the same partition data
concurrently. Requiring all other consumers to wait until all batches
have been fetched obviously causes slow-down as consumers can receive
partial data as its received.

## Solution
This PR solves these two problems by:
1. Cache population in separate task
- put the cache population in its own task and producer push batches
into the entry as it receives them.

2. Introduce streaming cache via `CacheEntry` and `EntryState`
- Struct that contains state and buffered data for new subscribers to
replay data that has been received and wait for new data to be pulled.

## Results / Benches
Some queries that are using broadcast see speedups 😄 

<img width="325" height="950" alt="Screenshot 2026-01-27 at 6 28 13 PM"
src="https://github.com/user-attachments/assets/f6754664-fab8-41e0-9a57-c61636901f75"
/>

and we definitively fixed the panic error on re-executing the same
partition. here is a before and after on a query that had this panic:

**Before:** we see the panic about partitions being executed multiple
times
<img width="1428" height="144" alt="Screenshot 2026-01-27 at 6 28 56 PM"
src="https://github.com/user-attachments/assets/3d5a8efd-2b0c-485e-b0d8-2253feccbad2"
/>

**After:** we no longer see it but see the arrow error as explained
below
<img width="1430" height="107" alt="Screenshot 2026-01-27 at 6 29 18 PM"
src="https://github.com/user-attachments/assets/1e5af5f9-13b1-4b9b-817b-667b3dafe78d"
/>

## IMPORTANT NOTE - DataFusion Regression
Some tpcds queries panic with:
```text
thread 'tokio-runtime-worker' panicked at .../h2-0.4.13/...:
state=Closed(ScheduledLibraryReset(CANCEL))
```
due to upstream error:
```text
Arrow error: Invalid argument error: column types must match schema types, 
expected Dictionary(UInt16, Utf8) but found Utf8 at column index 1
```
I have confirmed that this is an upstream DataFusion issue (which I may
or may not have time to do tonight 😅) and not related to broadcast, but
it unveiled it. I proved this by reproducing this error on single-node
DataFusion on the same data:

Prerequisite: have the tpcds data downloaded at some arbitrary location
1. Go to datafusion repo
2. run: `datafusion-cli`
3. use sql:
```sql
CREATE EXTERNAL TABLE store STORED AS PARQUET LOCATION 'path_to_tpcds_data/store';
SELECT s_county, s_state FROM store LIMIT 1;
```
4. You will see:
```text
Error: Arrow error: Invalid argument error: column types must match schema types, expected Dictionary(UInt16, Utf8) but found Utf8 at column index 1
```

When initially debugging this, I didn't see it in my single-node (I was
using 50.2.0). Then I realized we upgraded in distributed thus I
upgraded to (52.1.0) and the error occurs.

---------

Co-authored-by: Gabriel Musat Mestre <gabriel.musatmestre@datadoghq.com>